package com.pukaar.common;

public enum EmergencyStatus {
    TRIGGERED, LOCATION_ACQUIRED, CONTACTS_NOTIFIED, AUDIO_RECORDING_ACTIVE, SEGMENTS_UPLOADING, CALL_112_INITIATED, LIVE_LOCATION_ACTIVE, WAITING_SAFE, CLOSED
}
